---
- name: RPi2-Konfiguration
  hosts: localhost
  become: yes
  become_method: sudo
  roles:
    # Roles shall be configurable as needed
    - update
    - basis
    - other_services
    - human_tty
    - nextcloud
