---
- name: RPi2-Konfiguration
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    # These roles should always be included
    # —currently none—

    # Roles shall be configurable as needed
    - automatic_update

    #- update
    #- basis
    #- other_services
    #- human_tty
    #- nextcloud
