---
- name: Install required roles
  hosts: localhost
  vars_files:
    - vars/main.yml
  roles:
    - install_ansible_roles

- name: RPi2-Konfiguration
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    # These roles should always be included

    # Roles shall be configurable as needed
    - automatic_update

    #- update
    #- basis
    #- other_services
    #- human_tty
    #- nextcloud
