---
- name: RPi2-Konfiguration
  hosts: localhost
  become: yes
  become_method: sudo
  roles:
    # These roles should always be included
    - install_ansible_roles

    # Roles shall be configurable as needed

    #- update
    #- basis
    #- other_services
    #- human_tty
    #- nextcloud
    #trollollo