---
- name: Debian-Goodies installieren (für checkrestart)
  apt:
    name: debian-goodies
    state: present
- name: Create directories
  file:
    path: '{{rpi2_conf_automatic_reboot_script_path | dirname}}'
    state: directory
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
- name: Copy cronjob script
  copy:
    src: automatic_reboot.sh
    dest: '{{rpi2_conf_automatic_reboot_script_path}}'
    mode: u=rwx,g=r,o=r
    owner: root
    group: root

- name: Cron environment variable
  cronvar:
    cron_file: '{{rpi2_conf_automatic_reboot_cronfile_name}}'
    name: '{{item.name}}'
    value: '{{item.value}}'
  with_items:
    - name: FAILED_REBOOT_SINCE_FILE
      value: '{{rpi2_conf_failed_reboot_since_file}}'
    - name: FAILED_URGENT_REBOOT_SINCE_FILE
      value: '{{rpi2_conf_failed_urgent_reboot_since_file}}'
    - name: FAILED_REBOOT_TIMEOUT
      value: '{{rpi2_conf_failed_reboot_timeout}}'
    - name: FAILED_URGENT_REBOOT_TIMEOUT
      value: '{{rpi2_conf_failed_urgent_reboot_timeout}}'
    - name: TIME_TO_LOG_OUT
      value: '{{rpi2_conf_time_to_log_out}}'
    - name: NO_RESTART_NEEDED_OUTPUT
      value: '{{rpi2_conf_no_restart_needed_output}}'
    - name: REBOOT_WALL_MESSAGE
      value: '{{rpi2_conf_reboot_wall_message}}'
    - name: REBOOT_DEFERRED_MESSAGE
      value: '{{rpi2_conf_reboot_deferred_message}}'

- name: Cronjob
  cron:
    name: 'automatic reboot'
    cron_file: '{{rpi2_conf_automatic_reboot_cronfile_name}}'
    user: root
    job: '{{rpi2_conf_automatic_reboot_script_path}}'
    minute: 2,12,22,32,42,52
